/***********************************************************************/
/*                                                                     */
/*  FILE        :adc.c                                                 */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :Initialize A/D Convberter                             */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuhei KONDO.                            */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "stdio.h"
#include "math.h"
#include "interrupt_handlers.h"
#include "global.h"
#include "sci.h"
#include "adc.h"
#include "timer.h"
#include "pwm.h"
#include "encoder.h"
#include "queue.h"
#include "lineTrace.h"
#include "search.h"

static int adVal[8];

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :initAD0                                      */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Initialize Unit0 of 10bit A/D Convberter     */
/*                                                                     */
/***********************************************************************/
void initAD0(void)
{
  //	PORT0.ICR.BIT.B7 = 1;			// 外部ﾄﾘｶﾞ
                                                // PORT0.bit7(ADTRG0#端子)入力ﾊﾞｯﾌｧ有効
                                                // P07をA/D変換開始のﾄﾘｶﾞとして設定

  MSTP(AD0) = 0;				// AD0ﾕﾆｯﾄﾓｼﾞｭｰﾙｽﾀﾝﾊﾞｲ解除

  softDelay(10);				// 10ms待機

  AD0.ADCSR.BYTE = 0x00;			// A/Dｺﾝﾄﾛｰﾙ/ｽﾃｰﾀｽﾚｼﾞｽﾀの設定
						// 変換ﾁｬﾈﾙ：AN0

  //	AD0.ADCSR.BIT.ADIE = 1;			// A/D変換終了によるADI割り込み許可

  AD0.ADCR.BYTE = 0x0e;	       	                // A/Dｺﾝﾄﾛｰﾙﾚｼﾞｽﾀの設定(0000 1110)
                                                // 動作ﾓｰﾄﾞ：連続ｽｷｬﾝﾓｰﾄﾞ
                                                // 変換ｸﾛｯｸ：PCLK(48MHz)

  AD0.ADDPR.BIT.DPSEL = 0;		        // ﾃﾞｰﾀﾌｫｰﾏｯﾄ：LSB詰め

  AD0.ADSSTR = 24;			        // A/Dｻﾝﾌﾟﾘﾝｸﾞｽﾃｰﾄﾚｼﾞｽﾀの設定
                                                //（24(標準値)：PCLK=48MHz時で0.5μsとなる値)
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :initAD1                                      */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Initialize Unit1 of 10bit A/D Convberter     */
/*                                                                     */
/***********************************************************************/
void initAD1(void)
{
  MSTP(AD1) = 0;
  softDelay(10);
  AD1.ADCSR.BYTE = 0x00;
  //	AD0.ADCSR.BIT.ADIE = 1;
  AD1.ADCR.BYTE = 0x0e;
  AD1.ADDPR.BIT.DPSEL = 0;
  AD1.ADSSTR = 24;
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :initS12AD                                    */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Initialize 12bit A/D Convberter              */
/*                                                                     */
/***********************************************************************/
void initS12AD(void)
{
  MSTP(S12AD) = 0;		        // S12ADﾓｼﾞｭｰﾙｽﾀﾝﾊﾞｲ解除

  softDelay(10);			// 10ms待機(ﾏﾆｭｱﾙP1678)

  //	S12AD.ADSTRGR = 0x00;		// 外部ﾄﾘｶﾞ

  S12AD.ADANS.BIT.ANS = 0b00011111; 	        // CH0,1,2,3,4を変換対象

  S12AD.ADCSR.BIT.CKS = 0x03; 	        // S12ADのｸﾛｯｸをPCLK(48MHz)にする
  //	S12AD.ADCSR.BIT.ADIE = 1;	// ｽｷｬﾝ終了後のS12ADI0割り込み発生の許可

  S12AD.ADCSR.BIT.ADCS = 1;	        // 連続ｽｷｬﾝﾓｰﾄﾞ	

  S12AD.ADCER.BIT.ADRFMT = 0; 	        // ﾃﾞｰﾀﾌｫｰﾏｯﾄ：LSB詰め
  //	S12AD.ADCER.BIT.ACE = 1;	// ADDRnの読み出しによるADDRnの自動ｸﾘｱを許可
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :startAD0                                     */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Start Unit0 of 10bit A/D Convberter          */
/*                                                                     */
/***********************************************************************/
void startAD0(void)
{
  AD0.ADCSR.BIT.ADST = 1;			// AN0 AD変換開始
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :startAD1                                     */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Start Unit1 of 10bit A/D Convberter          */
/*                                                                     */
/***********************************************************************/
void startAD1(void)
{
  AD1.ADCSR.BIT.ADST = 1;			// AN1 AD変換開始
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :startS12AD                                   */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Start 12bit A/D Convberter                   */
/*                                                                     */
/***********************************************************************/
void startS12AD(void)
{
  S12AD.ADCSR.BIT.ADST = 1;		// S12AD A/D変換開始
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :getAdVal                                     */
/*  FUNCTION ARGUMENTS   :short                                        */
/*  RETURN VALUE         :short                                        */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Get 12bit ADC value                          */
/*                                                                     */
/***********************************************************************/
int getAdVal(unsigned char ch)
{
  return adVal[ch];
}

/***********************************************************************/
/*                                                                     */
/*  FUNCTION NAME        :setAdVal                                     */
/*  FUNCTION ARGUMENTS   :void                                         */
/*  RETURN VALUE         :void                                         */
/*  HEADER FILE          :adc.h                                        */
/*  DESCRIPTION          :Set 12bit ADC value                          */
/*                                                                     */
/***********************************************************************/
void setAdVal(void)
{
  adVal[0] = S12AD.ADDR0;
  adVal[1] = S12AD.ADDR1;
  adVal[2] = S12AD.ADDR2;
  adVal[3] = S12AD.ADDR3;
  adVal[4] = S12AD.ADDR4;
  adVal[5] = S12AD.ADDR5;
  adVal[6] = S12AD.ADDR6;
  adVal[7] = S12AD.ADDR7;
}
