/***********************************************************************/
/*                                                                     */
/*  FILE        :control.h                                             */
/*  DATE        :Thu, May 29, 2014                                     */
/*  DESCRIPTION :Header file of control.c                              */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuta KAMIO.                             */
/*                                                                     */
/***********************************************************************/

#ifndef __control__
#define __control__ 

typedef struct motorState{

  long  qTotalCount;
  float q;
  float dQ; 
  float qD;
  float dQD;

  float u;

  float KT;

  int timeOld;
  int qOld;

  short encPolarity;
  short pwmPolarity;
  short pwmOffset;
  short encOffset;
  float pwmVal;
}MOTOR;


typedef struct eso{
  float x;
  float xHat[3];
  float l[3];
  float b;
  float u;
  short first;
}ESO;


void initMotorParam(void);
void initMotorVariables(void);
void getMotorState(short n);
void setMotorPwmValue(short n, float pwmVal);

float motorTorque0(float tau);
float motorTorque1(float tau);

float doubleMotorTorque0(float tau);
float doubleMotorTorque1(float tau);

void wheelControl();

extern float x;
extern float phi;

extern float dX;
extern float dPhi;

extern ESO eso[4];
#endif


