/***********************************************************************/
/*                                                                     */
/*  FILE        :global.c                                              */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :Initialize Global Variable                            */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuhei KONDO.                            */
/*                                                                     */
/***********************************************************************/

#include "queue.h"
#include "control.h"

int rxSci0 = -1;
int txSci0;
char buff[80];

char sprintfBuff[80];



MOTOR wheelMotor[2];


short sendSerialFlag=0;
short newData;

short r0M[2]; 
short r1M[2]; 

short r0S[2]; 
short r1S[2]; 

int servoData[2];


