/***********************************************************************/
/*                                                                     */
/*  FILE        :hardware_setup.c                                      */
/*  DATE        :Wed, Aug 21, 2013                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuhei KONDO.                            */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "stdio.h"
#include "math.h"
#include "interrupt_handlers.h"
#include "global.h"
#include "sci.h"
#include "sci1.h"
#include "adc.h"
#include "timer.h"
#include "pwm.h"
#include "encoder.h"
#include "queue.h"
#include "lineTrace.h"
#include "search.h"

void HardwareSetup(void)
{
  SYSTEM.SCKCR.LONG = 0x00020100;			// ICLK=96MHz PCLK=48MHz

  /* フォトリフレクタ & LED & カラーセンサ入力 */
  PORTD.DDR.BYTE = 0b11111111;
  /* 12V LED */
  PORTA.DDR.BYTE = 0b11000111;
  PORTA.DR.BIT.B0 = 1;

  /* Hand switch */
  PORTE.DDR.BYTE = 0b00000000;
  PORTE.ICR.BYTE = 0b00000011;
  PORTE.PCR.BYTE = 0b00000011;

    /* 音声IC */
  PORT1.DDR.BIT.B2 = 0;
  PORT1.DDR.BIT.B3 = 0;

  PORT5.DDR.BIT.B0 = 0;
  PORT5.DDR.BIT.B1 = 0;
  PORT5.DDR.BIT.B2 = 0;
  PORT5.DDR.BIT.B3 = 0;
  PORT5.DDR.BIT.B4 = 0;
  PORT5.DDR.BIT.B5 = 0;
 

  initSCI0();//serial port
  initSCI1();//serial port

  initS12AD();

  initTMR01(1);
  initTMR23();

  initMTU0();	//encV
  initMTU6();	//encV

  initMTU1();	//enc
  initMTU7();	//enc

  initMTU8();	//double motor


  initMTU9();	//double motor

  initMTU4();	//mtR
  initMTU10();	//mtL

}
