/***********************************************************************/
/*                                                                     */
/*  FILE        :lineTrace.h                                           */
/*  DATE        :Thu, May 29, 2014                                     */
/*  DESCRIPTION :Line trace control header file                        */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuhei KONDO                             */
/*                                                                     */
/***********************************************************************/

#ifndef __LINETRACE__

#define __LINETRACE__

void setFtVal(void);
short getFtVal(short ftNum);
void onLinePD(void);
void LC(void);

#endif
