/***********************************************************************/
/*                                                                     */
/*  FILE        :pwm.h                                                 */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :Declarations of PWM function                          */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuta KAMIO.                             */
/*                                                                     */
/***********************************************************************/

#ifndef __PWM__

#define __PWM__

void initMTU3(void);
void initMTU4(void);
void initMTU8(void);
void initMTU9(void);
void initMTU10(void);
extern int direction[12];
void setFrequency(short channel,float frequency);
short getDirection(short channel);
void setDuty(short channel,float duty);
void setDutyDC(short channel,float duty);
void setDutyDoubleDC(short channel,float duty);
void startDcPWM(void);

#endif

