/***********************************************************************/
/*                                                                     */
/*  FILE        :pwm.c                                                 */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :PWM set up file                                       */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuta KAMIO.                             */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "stdio.h"
#include "math.h"
#include "stdlib.h"
#include "interrupt_handlers.h"
#include "global.h"
#include "sci.h"
#include "adc.h"
#include "timer.h"
#include "pwm.h"
#include "encoder.h"
#include "queue.h"
#include "lineTrace.h"
#include "search.h"

int direction[12]={0,0,0,0,0,0,0,0,0,0,0,0}; //pwm回転方向リスト

/************************************************************************/ 
/* function name : initMTU3                                             */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   PWM出力ポート     p24     		                                */
/*   PWM出力ポート     p24     		                                */
/*   設定周波数20kHz(TGRA=2400)		                                */
/************************************************************************/
void initMTU3(void)
{
  MSTP(MTU3) = 0;		//モジュールストップ解除

  MTU3.TCR.BIT.TPSC = 0;	//内部クロック：PCLK/1
  MTU3.TCR.BIT.CKEG = 0;	//カウント : 立ち上がりエッジ
  MTU3.TCR.BIT.CCLR = 1;	//TCNTクリア条件 : TGRA のコンペアマッチ

  MTU3.TMDR.BIT.MD = 2;		//モード設定 : PWMモード1

  MTU3.TIORH.BIT.IOA = 2;	//初期出力はLow出力 コンペアマッチでLow出力
  MTU3.TIORH.BIT.IOB = 5;	//初期出力はLow出力 コンペアマッチでHigh出力

  MTU3.TIORL.BIT.IOC = 2;	//初期出力はLow出力 コンペアマッチでLow出力
  MTU3.TIORL.BIT.IOD = 5;	//初期出力はLow出力 コンペアマッチでHigh出力


  MTU3.TGRA = 0x095F;		//PWM周波数設定 : 20kHz
  MTU3.TGRB = 0x00;		//duty比設定
  MTU3.TGRC = 0x095F;
  MTU3.TGRD = 0x00;


  MTU3.TIER.BIT.TGIEA = 1;	//割り込み許可
  MTU3.TIER.BIT.TGIEA = 1;	//割り込み許可

  IEN(MTU3,TGIA3) = 1; 		//割り込み許可
  IPR(MTU3,TGIA3) = 1; 		//割り込みレベル設定

  IEN(MTU3,TGIC3) = 1; 		//割り込み許可
  IPR(MTU3,TGIC3) = 1; 		//割り込みレベル設定

}


/************************************************************************/ 
/* function name : initMTU4                                             */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   PWM出力ポート     p24     		                                */
/*   PWM出力ポート     p24     		                                */
/*   設定周波数20kHz(TGRA=2400)		                                */
/************************************************************************/
void initMTU4(void)
{
  MSTP(MTU4) = 0;		//モジュールストップ解除

  MTU4.TCR.BIT.TPSC = 0;	//内部クロック：PCLK/1
  MTU4.TCR.BIT.CKEG = 0;	//カウント : 立ち上がりエッジ
  MTU4.TCR.BIT.CCLR = 1;	//TCNTクリア条件 : TGRA のコンペアマッチ

  MTU4.TMDR.BIT.MD = 2;		//モード設定 : PWMモード1

  MTU4.TIORH.BIT.IOA = 2;	//初期出力はLow出力 コンペアマッチでLow出力
  MTU4.TIORH.BIT.IOB = 5;	//初期出力はLow出力 コンペアマッチでHigh出力

  MTU4.TIORL.BIT.IOC = 2;	//初期出力はLow出力 コンペアマッチでLow出力
  MTU4.TIORL.BIT.IOD = 5;	//初期出力はLow出力 コンペアマッチでHigh出力


  MTU4.TGRA = 0x095F;		//PWM周波数設定 : 20kHz
  MTU4.TGRB = 0x00;		//duty比設定
  MTU4.TGRC = 0x095F;
  MTU4.TGRD = 0x00;

  MTUA.TOER.BIT.OE4C = 1;	//出力端子の出力許可
  MTUA.TOER.BIT.OE4A = 1;

  MTU4.TIER.BIT.TGIEA = 1;	//割り込み許可
  MTU4.TIER.BIT.TGIEA = 1;	//割り込み許可

  IEN(MTU4,TGIA4) = 1; 		//割り込み許可
  IPR(MTU4,TGIA4) = 1; 		//割り込みレベル設定

  IEN(MTU4,TGIC4) = 1; 		//割り込み許可
  IPR(MTU4,TGIC4) = 1; 		//割り込みレベル設定

}

/************************************************************************/ 
/* function name : initMTU8                                             */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   サーボモーター用                                                      */
/*   PWM出力ポート      PA6     		                                */
/*   回転方向出力ポート PA7	                                        */
/*   設定周波数50Hz(TGRA=937)	                   	                */
/************************************************************************/
void initMTU8(void)
{
//  MSTP(MTU8) = 0;
//  MTU8.TCR.BYTE = 0x27;
//  MTU8.TMDR.BYTE = 0x02;
//  MTU8.TIOR.BYTE = 0x21;
//  MTU8.TGRA = 0x03A9;
//  //  MTU8.TGRB = 0x358;
//  MTUB.TSTR.BIT.CST2 = 1;

  MSTP(MTU2) = 0;		//Module stop release
  MSTP(MTU8) = 0;		//Module stop release

  MTU2.TCR.BIT.TPSC = 0;	//Internal clock： PCLK/1
  MTU2.TCR.BIT.CKEG = 0;	//Count on the rising edge
  MTU2.TCR.BIT.CCLR = 1;	//TCNT cleared by compare match TGRA

  MTU8.TCR.BIT.TPSC = 0;	//Internal clock： PCLK/1
  MTU8.TCR.BIT.CKEG = 0;	//Count on the rising edge
  MTU8.TCR.BIT.CCLR = 3;	//TCNT cleared by another channel performing sychronous clearing -> MTU2.TGRA 

  MTU2.TMDR.BIT.MD = 0;	//PWM mode 2
  MTU8.TMDR.BIT.MD = 3;	//PWM mode 2

  MTU2.TIOR.BIT.IOA = 0;	//output prohibited
  MTU2.TIOR.BIT.IOB = 0;	//output prohibited


  MTU8.TIOR.BIT.IOA = 5;	//Initial output is High output , Low output at compare match
  MTU8.TIOR.BIT.IOB = 5;	//Initial output is High output , Low output at compare match


  MTUB.TSYR.BIT.SYNC2 = 1;
  MTUB.TSYR.BIT.SYNC3 = 1;

  


  MTU8.TGRA = 0x00;		//duty setting
  MTU8.TGRB = 0x00;		//duty setting

  //MTUA.TOCR1.BIT.PSYE = 1;
  //MTUB.TOCR1.BIT.PSYE = 1;

  MTU2.TIER.BIT.TGIEA = 1;	//Interrupt request

  IEN(MTU2,TGIA2) = 1;	//Interrupt request
  IPR(MTU2,TGIA2) = 1;	//Interrupt priority level 1


}

/************************************************************************/ 
/* function name : initMTU9                                             */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   サーボモーター用                                                      */
/*   PWM出力ポート      pB0     		                                */
/*   回転方向出力ポート pB1	                                        */
/*   設定周波数50Hz(TGRA=937)	                   	                */
/************************************************************************/
void initMTU9(void)
{
//  MSTP(MTU9) = 0;		//モジュールストップ解除  
//  MTU9.TCR.BIT.TPSC = 5;	//内部クロック：PCLK/1024
//  MTU9.TCR.BIT.CKEG = 0;	//カウント : 立ち上がりエッジ
//  MTU9.TCR.BIT.CCLR = 1;	//TCNTクリア条件 : TGRA のコンペアマッチ
//  MTU9.TMDR.BIT.MD = 2;	       	//モード設定 : PWMモード1
//  MTU9.TIORH.BIT.IOA = 1;	//初期出力はLow出力 コンペアマッチでLow出力
//  MTU9.TIORH.BIT.IOB = 2;	//初期出力はLow出力 コンペアマッチでHigh出力
//  MTU9.TGRA = 0x03A9;		//PWM周波数設定 : 50Hz  
//  MTUB.TSTR.BIT.CST3 = 1;	//カウント動作開始

  MSTP(MTU9) = 0;		//Module stop release

  MTU9.TCR.BIT.TPSC = 0;	//Internal clock： PCLK/1
  MTU9.TCR.BIT.CKEG = 0;	//Count on the rising edge
  MTU9.TCR.BIT.CCLR = 1;	//TCNT cleared by compare match TGRA

  MTU9.TMDR.BIT.MD = 2;	//PWM mode 1

  MTU9.TIORH.BIT.IOA = 2;	//Initial output is Low output , Low output at compare match
  MTU9.TIORH.BIT.IOB = 5;	//Initial output is Low output , High output at compare match

  MTU9.TIORL.BIT.IOC = 2;	//Initial output is Low output , Low output at compare match
  MTU9.TIORL.BIT.IOD = 5;	//Initial output is Low output , High output at compare match


  MTU9.TGRA = 0x095F;		//20kHz
  MTU9.TGRB = 0x0000;		//duty setting

  MTU9.TGRC = 0x095F;		//20kHz
  MTU9.TGRD = 0x0000;		//duty setting

  MTU9.TIER.BIT.TGIEA = 1;	//Interrupt request
  MTU9.TIER.BIT.TGIEC = 1;	//Interrupt request

  IEN(MTU9,TGIA9) = 1;	//Interrupt request
  IPR(MTU9,TGIA9) = 1;	//Interrupt priority level 1

  IEN(MTU9,TGIC9) = 1;	//Interrupt request
  IPR(MTU9,TGIC9) = 1;	//Interrupt priority level 1

}

/************************************************************************/ 
/* function name : initMTU10                                            */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   PWM出力ポート      pB4     		                                */
/*   回転方向出力ポート pB5	                                        */
/*   設定周波数20kHz(TGRA=2400)		                                */
/************************************************************************/
void initMTU10(void)
{

  MSTP(MTU10) = 0;		//Module stop release

  MTU10.TCR.BIT.TPSC = 0;	//Internal clock： PCLK/1
  MTU10.TCR.BIT.CKEG = 0;	//Count on the rising edge
  MTU10.TCR.BIT.CCLR = 1;	//TCNT cleared by compare match TGRA

  MTU10.TMDR.BIT.MD = 2;	//PWM mode 1

  MTU10.TIORH.BIT.IOA = 2;	//Initial output is Low output , Low output at compare match
  MTU10.TIORH.BIT.IOB = 5;	//Initial output is Low output , High output at compare match

  MTU10.TIORL.BIT.IOC = 2;	//Initial output is Low output , Low output at compare match
  MTU10.TIORL.BIT.IOD = 5;	//Initial output is Low output , High output at compare match


  MTU10.TGRA = 0x095F;		//20kHz
  MTU10.TGRB = 0x0000;		//duty setting

  MTU10.TGRC = 0x095F;		//20kHz
  MTU10.TGRD = 0x0000;		//duty setting

  MTUB.TOER.BIT.OE4A = 1;	//PWM output enable
  MTUB.TOER.BIT.OE4C = 1;	//PWM output enable


  MTU10.TIER.BIT.TGIEA = 1;	//Interrupt request
  MTU10.TIER.BIT.TGIEC = 1;	//Interrupt request


  IEN(MTU10,TGIA10) = 1;	//Interrupt request
  IPR(MTU10,TGIA10) = 1;	//Interrupt priority level 1

  IEN(MTU10,TGIC10) = 1;	//Interrupt request
  IPR(MTU10,TGIC10) = 1;	//Interrupt priority level 1


}

/************************************************************************/ 
/* function name : setFrequency                                         */
/* function arguments : short channel, double frequency                 */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   PWM周波数設定関数                                                     */
/*   channel   : 設定するチャンネルを入力（4,9,10)	                        */
/*   frequency : 設定する周波数を入力		                        */
/*	 0x0258→20kHz, 0x04B0→10kHz                                     */
/*	 0x016A→50Hz	                                                */
/************************************************************************/
void setFrequency(short channel,float frequency)
{
  long periodAddress[] = {0,0,0x00088808,0,0x0008861C,0,0,0,0,0x00088A18,0x00088A1C,0};	//TGRAのアドレス
  *((volatile unsigned short *)periodAddress[channel]) = frequency;			//周期設定
}


void setDutyDC(short channel, float duty)
{
  float abDuty = 0;

  short dir;

  long TGRA_ADDRESS_4_10[]={0x0008861C, 0x00088A1C};
  long TGRB_ADDRESS_4_10[]={0x0008861E, 0x00088A1E};

  long TGRC_ADDRESS_4_10[]={0x00088628, 0x00088A28};
  long TGRD_ADDRESS_4_10[]={0x0008862A, 0x00088A2A};

  abDuty = fabs(duty);

  if(0.8 <= abDuty){	//duty比を80%以下に設定
    abDuty = 0.8;
  }

  if(duty > 0)
    dir = 0;
  else
    dir = 1;

  *((volatile unsigned short*) TGRB_ADDRESS_4_10[channel]) = (short) (*((volatile unsigned short*) TGRA_ADDRESS_4_10[channel]))*abDuty*dir;
  *((volatile unsigned short*) TGRD_ADDRESS_4_10[channel]) = (short) (*((volatile unsigned short*) TGRC_ADDRESS_4_10[channel]))*abDuty*(1-dir);
  
}

void setDutyDoubleDC(short channel, float duty)
{
  float abDuty = 0;

  short dir;

  long TGRA_ADDRESS_4_10_8_9[]={0x0008861C, 0x00088A1C, 0x00088A18, 0x00088A18};//MTU4_TGRA, MTU10_TGRA, MTU9_TGRA, MTU9_TGRA
  long TGRB_ADDRESS_4_10_8_9[]={0x0008861E, 0x00088A1E, 0x00088C08, 0x00088A1A};//MTU4_TGRB, MTU10_TGRB, MTU8_TGRA, MTU9_TGRB
 

  long TGRC_ADDRESS_4_10_8_9[]={0x00088628, 0x00088A28, 0x00088A18, 0x00088A24};//MTU4_TGRC, MTU10_TGRC, MTU9_TGRA, MTU9_TGRC
  long TGRD_ADDRESS_4_10_8_9[]={0x0008862A, 0x00088A2A, 0x00088C0A, 0x00088A26};//MTU4_TGRD, MTU10_TGRD, MTU8_TGRB, MTU9_TGRD

  abDuty = fabs(duty);

  if(0.8 <= abDuty){	//duty比を80%以下に設定
    abDuty = 0.8;
  }

  if(duty > 0)
    dir = 0;
  else
    dir = 1;

  *((volatile unsigned short*) TGRB_ADDRESS_4_10_8_9[channel]) = (short) (*((volatile unsigned short*) TGRA_ADDRESS_4_10_8_9[channel]))*abDuty*dir;
  *((volatile unsigned short*) TGRD_ADDRESS_4_10_8_9[channel]) = (short) (*((volatile unsigned short*) TGRC_ADDRESS_4_10_8_9[channel]))*abDuty*(1-dir);
  
}


/************************************************************************/ 
/* function name : setDuty                                              */
/* function arguments : short channel, double duty                      */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*   duty比設定関数	                                                */
/*   channel   : 設定するチャンネルを入力（4,9,10)	                        */
/*   duty      : 設定するduty比を入力(-1.0～1.0)       	                */
/*	      duty比 正:回転方向出力　1	                                */
/* 	             負:回転方向出力　0	                                */
/*				                                        */
/************************************************************************/
void setDuty(short channel, float duty)
{
  float abDuty = 0;	//duty比の絶対値

  long periodAddress[] = {0,0,0,0,0x0008861C,0,0,0,0x00088C08,0x00088A18,0x00088A1C,0};	//TGRAのアドレス
  long dutyAddress[]   = {0,0,0,0,0x0008861E,0,0,0,0x00088C0A,0x00088A1A,0x00088A1E,0};	//TGRBのアドレス

  if(0 <= duty){	//回転方向を出力
    direction[channel] = 1;
  }else{ 
    direction[channel] = 0;
  }

  abDuty = fabs(duty);

  if(0.8 <= abDuty){	//duty比を80%以下に設定
    abDuty = 0.8;
  }

  abDuty = 1-abDuty;

  if(1 == abDuty){
    abDuty = 1.2;
  }

  *((volatile unsigned short *)dutyAddress[channel]) = (short)(abDuty * (*((volatile unsigned short *)periodAddress[channel])));
}

/************************************************************************/ 
/* function name : getDirection                                         */
/* function arguments : short channel                                   */
/* return value : short                                                 */
/* header file : pwm.h		                                        */
/* description :	       	  	                                */
/*				                                        */
/************************************************************************/
short getDirection(short channel)
{
  return direction[channel];
}


void startDcPWM(void)
{
  MTUA.TSTR.BIT.CST2 = 1;//start MTU2 counter
  MTUA.TSTR.BIT.CST3 = 1;//start MTU3 counter
  MTUA.TSTR.BIT.CST4 = 1;//start MTU4 counter

  MTUB.TSTR.BIT.CST2 = 1;//start MTU8 counter
  MTUB.TSTR.BIT.CST3 = 1;//start MTU9 counter
  MTUB.TSTR.BIT.CST4 = 1;//start MTU10 counter
 
}
