/***********************************************************************/
/*                                                                     */
/*  FILE        :queue.h                                               */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :                                                      */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Luis Canete.                             */
/*                                                                     */
/***********************************************************************/

#ifndef __QUEUE__
#define __QUEUE__

#define QUEUE_SIZE 160

typedef struct queue{
  char fifo[QUEUE_SIZE];
  int head;
  int tail;
  int max;
  short semaphore;
}QUEUE;

short enqueue(QUEUE *q,short data);
short dequeue(QUEUE *q);

#endif

