/***********************************************************************/
/*                                                                     */
/*  FILE        :queue.c                                               */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :                                                      */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Luis Canete.                             */
/*                                                                     */
/***********************************************************************/

#include "queue.h"

short enqueue(QUEUE *q,short data)
{

  if(q->max <= (q->tail - q->head))
    return -1;

  q->fifo[q->tail%q->max] = data;
  q->tail++;


  return 1;
}    

short dequeue(QUEUE *q)
{
  short retval = -1;

  if(q->head >= q->tail || q->semaphore == 1)
    return -1;

  retval = q->fifo[q->head%q->max];
  q->head++;

  if(q->head == q->tail)
    q->head = q->tail = 0;

  return retval;

}
