/***********************************************************************/
/*                                                                     */
/*  FILE        :sci.c                                                 */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :Serial Port Initialize                                */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Shuhei KONDO.                            */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "stdio.h"
#include "math.h"
#include "interrupt_handlers.h"
#include "global.h"
#include "sci.h"
#include "adc.h"
#include "timer.h"
#include "pwm.h"
#include "encoder.h"
#include "queue.h"
#include "lineTrace.h"
#include "search.h"

static  QUEUE txFifo = {.head = 0, .tail = 0, .max = QUEUE_SIZE};
static  QUEUE rxFifo = {.head = 0, .tail = 0, .max = QUEUE_SIZE};
//static  short txSemaphore;

/* Function name      : initSCI0
 * Function arguments : none
 * Return value       : none 
 * Header file        : sci.h 
 *
 * Function desciption:
 * Initializes SCI0 as an RS-232C compatible serial port. The current setting
 * is for 57600 baud in 8n1 format or 8-bits, no parity, 1 stop bit format. 
 * The port is a 3.3V level serial port.
 */
void initSCI0(void)
{
  int w_count;	        // 1bit期間待ち用ｶｳﾝﾀ

  MSTP(SCI0) = 0;	        // SCI0モジュールストップ解除
  PORT2.DDR.BIT.B1 = 0;
  PORT2.ICR.BIT.B1 = 1;	// 端子入力バッファ有効
  //PORT2.PCR.BIT.B1 = 1;
  //PORT2.ODR.BIT.B0 = 1; // OPEN drain output

  SCI0.SCR.BYTE = 0x00;	        // SCI0シリアルコントロールレジスタ設定
                                // クロックソース：内部クロック
                                // 送受信割り込み、送受信動作ともに禁止

  SCI0.SMR.BYTE = 0x00;	        // SCI0シリアルモードレジスタ設定
                                // クロック分周比：PCLK/1、調歩同期式、
                                // 8ビット長、奇数パリティあり、1ストップビット

  SCI0.BRR = 12;	        // SCI0ビットレートレジスタ設定
	                        // PCLK=48MHz

  for (w_count = 0; w_count < 1303; w_count++);	// 1bit転送期間ｳｪｲﾄ(ICLK=96MHz)

  
  SCI0.SCR.BYTE = 0x30;	        // 送受信割り込みの許可と送受信動作の許可
  SCI0.SCR.BYTE |= 0xC0;	        // 送受信割り込みの許可と送受信動作の許可

  IEN(SCI0, RXI0) = 1;	        // SCI0受信データフル割り込み(RXI1)許可
  IEN(SCI0, ERI0) = 1;	        // SCI0受信エラー割り込み(ERI1)許可
  IEN(SCI0,TXI0) = 1;   	// SCI0送信データエンプティ割り込み(TXI1)許可

  /* SCI1割り込みの初期化 */
  IPR(SCI0,) = 7;	        // SCI0割り込み優先レベル=7
 
  IR(SCI0, TXI0) = 0;	        // SCR.TIEﾋﾞｯﾄとSCR.TEﾋﾞｯﾄのｾｯﾄにより
                                // 発生するTXI1割り込み要求をクリア
}

/* Function name      : sci0Getc
 * Function arguments : none
 * Return value       : short 
 * Header file        : sci.h 
 *
 * Function desciption:
 * Gets a single character from the receive FIFO.
 * This is a none blocking function and returns a -1 when
 * data is not available from the FIFO.
 */
short sci0Getc()
{
  return (dequeueRx0());
}

/* Function name      : sci0Putc
 * Function arguments : short data
 * Return value       : short 
 * Header file        : sci.h 
 *
 * Function desciption:
 * sci0Putc places a single character from data into the transmit
 * FIFO txFiFo. The function returns a -1 when the FIFO is full and 
 * can no longer enqueue into the FIFO.
 */
short sci0Putc(short data)
{
  return (enqueueTx0(data));
}

/* Function name      : sci0Puts
 * Function arguments : short data
 * Return value       : none
 * Header file        : sci.h 
 *
 * Function desciption:
 * sci0Puts uses sci0Putc to send a string of characters to SCI0 port.
 */
void sci0Puts(char *buff)
{
  while (*buff != '\0') {
    if (sci0Putc(*buff) == 1)
      buff++;
  }
}

/* Function name      : sci1Write
 * Function arguments : char *, short 
 * Return value       : none
 * Header file        : sci.h 
 *
 * Function desciption:
 * sci1Puts uses sci1Putc to send a string of characters to SCI1 port.
 */
void sci0Write(char *buff, short n)
{
  short i;

  for(i = 0 ;i < n ; i++)
  {
    if (sci0Putc(*buff) == 1)
      buff++;
  }

}

/* Function name      : enqueueTx
 * Function arguments : short data
 * Return value       : short
 * Header file        : sci.h 
 *
 * Function desciption:
 * enqueueTx is a function used to access txFifo QUEUE structure.
 * enqueueTx returns 1 for successful enqueue of variable data
 * and returns -1 for failed enqueue.
 */
short enqueueTx0(short data)
{
  short retVal = 1;

  txFifo.semaphore = 1;
  retVal = enqueue(&txFifo,data);

  if(SCI0.SSR.BIT.TDRE == 1) {
      txFifo.semaphore = 0;
      SCI0.TDR = dequeue(&txFifo); 
  }

  txFifo.semaphore = 0;

  return retVal;
} 

/* Function name      : dequeueTx
 * Function arguments : none
 * Return value       : short
 * Header file        : sci.h 
 *
 * Function desciption:
 * dequeueTx is a function used to access rxFifo from other files
 * especially interrupt routines. It returns -1 if the FIFO/QUEUE
 * is empty.
 */
short dequeueTx0()
{
  return (dequeue(&txFifo)); 
}

/* Function name      : enqueueRx
 * Function arguments : short data
 * Return value       : short
 * Header file        : sci.h 
 *
 * Function desciption:
 * enqueueTx is a function used to access txFifo QUEUE structure from
 * other files. enqueueTx returns 1 for successful enqueue of the variable 
 * data and returns -1 for failed enqueue.
 */
short enqueueRx0(short data)
{
  return (enqueue(&rxFifo,data));
}

/* Function name      : dequeueRx
 * Function arguments : none
 * Return value       : short
 * Header file        : sci.h 
 *
 * Function desciption:
 * dequeueRx is a function used to access rxFifo QUEUE structure from 
 * other files. dequeueRx returns 1 for successful deuque of the variable 
 * data and returns -1 if the FIFO/QUEUE is empty.
 */
short dequeueRx0()
{
  return (dequeue(&rxFifo)); 
}


