/***********************************************************************/
/*                                                                     */
/*  FILE        :timer.c                                               */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :                                                      */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Kahori ANZAI                             */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "stdio.h"
#include "math.h"
#include "interrupt_handlers.h"
#include "global.h"
#include "sci.h"
#include "adc.h"
#include "timer.h"
#include "pwm.h"
#include "encoder.h"
#include "queue.h"
#include "lineTrace.h"
#include "search.h"

void initCMT(void)
{
  /* CMT コンペアマッチタイマ */
  SYSTEM.MSTPCRA.BIT.MSTPA15 = 0;	// モジュールストップ解除CMT0,CMT1
  //MSTP(CMT0) = 0;
  //MSTP(CMT1) = 0;

  /* クロック選択 0:PCLK/8 1:PCLK/32 2:PCLK/128 3:PCLK/512 */
  CMT1.CMCR.BIT.CKS = 3;		// 48MHz/512=93.75KHz  1周期=10.67μsec
  //CMT1.CMCOR = 46875;		        // 周期設定 46875x10.67=0.5sec
  CMT1.CMCOR = 46875/5;		        // 周期設定 46875/5x10.67=0.1sec
  CMT1.CMCNT = 0;			// カウンタリセット
 
  IEN(CMT1,CMI1) = 1;   	        // 割り込み要求許可
  IPR(CMT1,CMI1) = 1;		        // 割り込み優先レベル
}

/***********************************************************************
<initTMR01>
 :TMR01の初期設定
 :TMR0,TMR1を接続し16bitとしている
  +-----------------  1ms  ----------------+
  | PCLK/8 = 48MHz/8                       |
  | 48MHz/8 = 6MHz                         |
  | 1ms/1/6M = 6000 = 0x1770               |
  +----------------------------------------+
************************************************************************/

void initTMR01(unsigned char ms)
{
  int msCnt = 0x1770;		// 1msが何クロック分か
  int msSet;
  msSet = ms * msCnt;

  MSTP(TMR0) = 0;	        // モジュールストップ解除
  MSTP(TMR1) = 0;

  TMR01.TCCR = 0x180A;		// TMR0>TMR1のovf,TMR1>PCLK/8,モード>16BITモード
  TMR01.TCORA = msSet;		// CMTA 1ms*(1~10)
  TMR01.TCNT = 0x0000;		// カウンタ初期化
  TMR0.TCR.BYTE = 0x48;		// コンペアマッチA割り込みを許可,Aでクリア 
  TMR1.TCR.BYTE = 0x28;		// ovf割り込み許可,Aでクリア        
  TMR0.TCSR.BYTE = 0xD9;		// AD>x,出力A>high,B>low
  
  IR(TMR0,CMIA0) = 0;		//　割り込みフラグ
  IPR(TMR0,CMIA0) = 6;		//  割り込み優先度
  IEN(TMR0,CMIA0) = 1;		//  割り込み要求許可
}

void initTMR23(void)
{
  MSTP(TMR2) = 0;
  MSTP(TMR3) = 0;
  
  TMR2.TCORA = 0x4A;
  TMR3.TCORA = 0x09;

  TMR2.TCR.BIT.CCLR = 1;
  TMR3.TCR.BIT.CCLR = 1;

  TMR2.TCCR.BYTE = 0x0C;
  TMR3.TCCR.BIT.CSS = 3;
  
  TMR3.TCR.BIT.CMIEA = 1;

  IEN(TMR3,CMIA3) = 1;
  IPR(TMR3,CMIA3) = 1;
}

void softDelay(int ms)
{
  unsigned long int i;

  for(i=0; i<(6850*ms); i++);
}



