/***********************************************************************/
/*                                                                     */
/*  FILE        :timer.h                                               */
/*  DATE        :Tue, Nov 19, 2013                                     */
/*  DESCRIPTION :                                                      */
/*  CPU TYPE    :RX621                                                 */
/*                                                                     */
/*  This file is generated by Kahori ANZAI                             */
/*                                                                     */
/***********************************************************************/

#ifndef __TIMER__

#define __TIMER__

void initCMT(void);
void initTMR01(unsigned char ms);
void initTMR23(void);
void softDelay(int ms);
void delay(int ms);

#endif
